---
- name: Create image directory
  file: path="{{ image_tars_dir }}/charts" state=directory

- name: Copy charts docker image tars
  synchronize:
    src: "{{ charts_image_tars_dir }}/"
    dest: "{{ image_tars_dir }}/charts"
    checksum: yes

- name: Find docker images
  find:
    paths: "{{ image_tars_dir }}/charts"
    patterns: '*.tar'
  register: charts_images_result

- name: Load docker images
  shell: |
    docker load -i "{{ item.path }}"
  with_items: "{{ charts_images_result.files }}"

- name: Remove chart docker image tars
  file: path="{{ image_tars_dir }}/charts" state=absent
