- name: Create image directory
  file: path="{{ image_tars_dir }}/cluster" state=directory

- name: Copy cluster docker image tars
  synchronize:
    src: "{{ cluster_image_tars_dir }}/"
    dest: "{{ image_tars_dir }}/cluster"
    checksum: yes

- name: Find docker images
  find:
    paths: "{{ image_tars_dir }}/cluster"
    patterns: '*.tar'
  register: cluster_images_result

- name: Load docker images
  shell: |
    docker load -i "{{ item.path }}"
  with_items: "{{ cluster_images_result.files }}"

- name: Remove cluster docker image tars
  file: path="{{ image_tars_dir }}/cluster" state=absent
