---
- name: Create image directory
  file: path="{{ image_tars_dir }}/glusterfs" state=directory

- name: Copy glusterfs docker image tars
  synchronize:
    src: "{{ glusterfs_image_tars_dir }}/"
    dest: "{{ image_tars_dir }}/glusterfs"
    checksum: yes

- name: Find docker images
  find:
    paths: "{{ image_tars_dir }}/glusterfs"
    patterns: '*.tar'
  register: glusterfs_images_result

- name: Load docker images
  shell: |
    docker load -i "{{ item.path }}"
  with_items: "{{ glusterfs_images_result.files }}"

- name: Retag heketi image
  shell: |
    docker tag {{ heketi_image }} docker.io/heketi/heketi:dev
