---
- name: Create image directory
  file: path="{{ image_tars_dir }}/harbor" state=directory

- name: Copy harbor docker image tars
  synchronize:
    src: "{{ harbor_image_tars_dir }}/"
    dest: "{{ image_tars_dir }}/harbor"
    checksum: yes

- name: Find docker images
  find:
    paths: "{{ image_tars_dir }}/harbor"
    patterns: '*.tar'
  register: harbor_images_result

- name: Load docker images
  shell: |
    docker load -i "{{ item.path }}"
  with_items: "{{ harbor_images_result.files }}"

