---
- name: Create image directory
  file: path="{{ image_tars_dir }}/harbor" state=directory

- name: Copy harbor docker image tars
  synchronize:
    src: "{{ harbor_image_tars_dir }}/"
    dest: "{{ image_tars_dir }}/harbor"
    checksum: yes

- name: Load docker images
  shell: |
    docker load -i {{ item.src }}
  with_filetree: "{{ image_tars_dir }}/harbor"
  when:
    - item.state == 'file'

- name: Remove harbor docker image tars
  file: path="{{ image_tars_dir }}/harbor" state=absent
