- name: Create image directory
  file: path={{ ecp_image_dir }} state=directory

- name: Copy docker images to all hosts
  synchronize:
    src: "{{ ecp_docker_images }}"
    dest: "{{ ecp_image_dir }}"
    checksum: yes

- name: Load docker images
  shell: |
    docker load -i {{ item.src }}
  with_filetree: "{{ ecp_image_dir }}"
  when:
    - item.state == 'file'

