---
- name: Create image directory
  file: path="{{ image_tars_dir }}/management" state=directory

- name: Copy management docker image tars
  synchronize:
    src: "{{ management_image_tars_dir }}/"
    dest: "{{ image_tars_dir }}/management"
    checksum: yes

- name: Find docker images
  find:
    paths: "{{ image_tars_dir }}/management"
    patterns: '*.tar'
  register: management_images_result

- name: Load docker images
  shell: |
    docker load -i "{{ item.path }}"
  with_items: "{{ management_images_result.files }}"

- name: Remove management docker image tars
  file: path="{{ image_tars_dir }}/management" state=absent
