---
- name: Uninstall old docker
  when: ansible_os_family == "RedHat"
  shell: |
    yum remove -y docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine

- name: Create rpm directory
  file: path={{ rpm_dir }} state=directory

- name: Copy rpm files to all hosts
  copy:
    src: "{{ item }}/"
    dest: "{{ rpm_dir }}"
  with_items:
    - "{{ docker_rpms_dir }}"
    - "{{ rsync_rpms_dir }}"

- name: Get the list of rpms
  shell: |
    ls -d -1 {{ rpm_dir }}/*.rpm
  register: rpm_list

- name: Install offline package
  when:
    - ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ rpm_list.stdout_lines }}"

- name: Remove rpms
  file: path="{{ rpm_dir }}" state=absent
