---
- name: Uninstall old docker
  when: ansible_os_family == "RedHat"
  shell: |
    yum remove -y docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine \
                  docker-ce

- name: Install yum-utils
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    
- name: Add stable repository
  when: ansible_os_family == "RedHat"
  shell: |
    yum-config-manager --add-repo {{ yum_docker_repo }}

- name: Install docker
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ required_softwares }}"

