---
- name: Install binaries online
  import_tasks: online.yml
  when: offline is not defined or not offline | bool

- name: Install binaries offline
  import_tasks: offline.yml
  when:
    - offline is defined
    - offline | bool

- name: Config docker
  template: src=docker.j2 dest={{ system_env_dir }}/docker 
  
- name: Config docker
  shell: |
    sed -i 's@ExecStart=/usr/bin/dockerd@ExecStart=/usr/bin/dockerd \"--insecure-registry=registry.harbor:5000\"@' /lib/systemd/system/docker.service
  when:
    - offline is defined
    - offline | bool

- name: Enable and restart Docker engine
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker

- name: Copy jq binary
  copy:
    src: "../binary/jq-linux64"
    dest: "/usr/bin/jq"
    mode: 0755

