---
- name: Copy calicoctl binary
  copy:
    src: "../binary/calicoctl"
    dest: "{{ network_dir }}"
    mode: 0755

- name: Validate calico profile, timeout in 5 minutes
  command: "{{ network_dir }}/calicoctl get profile"
  environment:
    ETCD_ENDPOINTS: "{{ etcd_endpoints }}"
  register: get_calico_profile
  until: 
    - get_calico_profile.stdout.find("k8s_ns.default") != -1
    - get_calico_profile.stdout.find("k8s_ns.kube-system") != -1
  retries: 60
  delay: 5

