---
- name: Copy calicoctl binary
  copy:
    src: "../binary/calicoctl"
    dest: "{{ network_dir }}"
    mode: 0755

- name: Validate calico profile, timeout in 5 minutes
  shell: |
    DATASTORE_TYPE=kubernetes KUBECONFIG=/root/.kube/config {{ network_dir }}/calicoctl get profile
  register: get_calico_profile
  until: 
    - get_calico_profile.stdout.find("kns.default") != -1
    - get_calico_profile.stdout.find("kns.kube-system") != -1
  retries: 60
  delay: 5

