- name: Check node readiness
  shell: |
    kubectl get node --no-headers=true | awk '{print $2}' | grep Ready | wc -l
  register: get_ready
  until: get_ready.stdout | int == cluster_hosts | length
  retries: 20
  delay: 15

