- name: Check node readiness
  shell: |
    kubectl get node --no-headers=true | awk '{print $2}' | grep Ready | wc -l
  register: get_ready
  until: get_ready.stdout | int == cluster_hosts | length
  retries: 20
  delay: 15

- name: Get kube api server IP
  shell: |
    kubectl describe pod kube-apiserver-{{ ansible_hostname }} \
            --namespace=kube-system | grep advertise-address | awk -F'=' '{print $2}'
  register: get_api_server
  until: get_api_server.stderr == "" and get_api_server.stdout != ""
  retries: 20
  delay: 15
  tags:
    - set_k8s_api_server

- name: Set master run fact
  set_fact:
    kube_api_server: "{{ get_api_server.stdout }}"
  tags:
    - set_k8s_api_server

