---
- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: prerequisite, tags: prerequisite }

- hosts: masters[0]
  gather_facts: yes
  become: yes
  roles:
    - { role: master, tags: master }
    - { role: cni, tags: cni }

- hosts: workers
  gather_facts: no
  become: yes
  roles:
    - { role: worker, tags: worker }

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - { role: label, tags: label }
    - { role: addon, tags: addon }

- hosts: cluster
  become: yes
  gather_facts: yes
  roles:
    - { role: glusterfs, tags: glusterfs}
    
- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: harbor, tags: harbor }

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - { role: ecp, tags: ecp }

