---
- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: prerequisite, tags: prerequisite }
    
- hosts: gpu
  gather_facts: no
  become: yes
  roles:
    - { role: nvidia, tags: nvidia }

- hosts: masters
  gather_facts: yes
  become: yes
  roles:
    - { role: etcd, tags: etcd }
    - { role: master, tags: master }
    - { role: cni, tags: cni }
    - { role: candidate, tags: candidate }
    - { role: vip, tags: vip }

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: worker, tags: worker }
    
- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - { role: addon, tags: addon }
    
- hosts: gpu
  gather_facts: no
  become: yes
  roles:
    - { role: deviceplugin, tags: deviceplugin }

- hosts: cluster
  become: yes
  gather_facts: yes
  roles:
    - { role: glusterfs, tags: glusterfs}
    
- hosts: masters
  become: yes
  gather_facts: yes
  roles:
    - { role: sharedir, tags: sharedir}
    
- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: harbor, tags: harbor }

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - { role: ecp, tags: ecp }

