---
- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: prerequisite, tags: prerequisite }

- hosts: masters
  gather_facts: yes
  become: yes
  roles:
    - { role: etcd, tags: etcd }
    - { role: master, tags: master }
    - { role: cni, tags: cni }
    - { role: candidate, tags: candidate }
    - { role: vip, tags: vip }
    - { role: replacebin, tags: replacebin }

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: worker, tags: worker }
    - { role: replacebin, tags: replacebin }

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - { role: addon, tags: addon }

- hosts: cluster
  become: yes
  gather_facts: yes
  roles:
    - { role: glusterfs, tags: glusterfs }
    
- hosts: masters
  become: yes
  gather_facts: yes
  roles:
    - { role: sharedir, tags: sharedir }
    
- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: harbor, tags: harbor }

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - { role: updatechart, tags: updatechart }
    - { role: ecp, tags: ecp }
