---

- hosts: cluster
  gather_facts: no
  become: yes
  tasks:
    - name: Reset Kubernetes component
      shell: "kubeadm reset"
      ignore_errors: True

    - name: Remove kubeadmin
      yum: name={{item}} state=removed
      with_items:
        - kubectl
        - kubeadm
        - kubelet
        - kubernetes-cni
      ignore_errors: True

    - name: Remove data directory
      file: path={{item}} state=absent
      with_items:
        - /var/lib/kubelet
        - /etc/kubernetes
        - /var/etcd
        - /var/lib/etcd
      ignore_errors: True

    - name: Flush IP tables
      iptables:
        table: nat
        flush: true
      ignore_errors: True
        
    - name: Restart docker services
      systemd:
        state: restarted
        name: docker
        daemon_reload: yes

