---

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: master, tags: master }
    - { role: cni, tags: cni }

- hosts: node
  gather_facts: no
  become: yes
  roles:
    - { role: node, tags: node }

- hosts: master
  gather_facts: no
  become: yes
  roles:
    - { role: addon, tags: addon }
    - { role: ecp, tags: ecp }
