---
- hosts: masters
  gather_facts: yes
  become: yes
  roles:
    - { role: upgrade_master, tags: master }

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: upgrade_worker, tags: worker }

- hosts: new_workers
  gather_facts: yes
  become: yes
  roles:
    - { role: upgrade_worker, tags: new_worker }
