---
# Docker registry
registry_domain: docker.io

# ECP namespace
ecp_namespace: sky-firmament

# ECP images
# appstore
rudder_image: docker.io/rivernet/rudder:20170626
tiller_image: docker.io/rivernet/tiller:v2.2.3
# logging
canes_image: docker.io/rivernet/canes:20170626
elasticsearch_image: docker.io/rivernet/elasticsearch:1.5.2
fluentd_image: docker.io/rivernet/fluentd-elasticsearch:1.22
# events
events_image: docker.io/rivernet/events:20170626
# license
license_image: docker.io/rivernet/license:20170626
# lyra
lyra_image: docker.io/rivernet/lyra:20170626
# mysql
mysql_image: docker.io/rivernet/mysql-sky:20170626
# prometheus
grafana_image: docker.io/rivernet/grafana-sky:20170626
docker_image: docker.io/rivernet/docker
kubestatemetrics_image: quay.io/coreos/kube-state-metrics:v0.5.0
nodeexporter_image: quay.io/prometheus/node-exporter:0.12.0
kubeapiexporter_image: docker.io/rivernet/kube-api-exporter
prometheus_image: quay.io/prometheus/prometheus:v1.5.2
# pyxis
pyxis_image: docker.io/rivernet/pyxis:20170626
# river
river_image: docker.io/rivernet/river:20170626
# sas
keystone_image: docker.io/rivernet/keystone:20161108
sas_image: docker.io/rivernet/skyform-sas:20170626

