---
- name: Install binaries online
  import_tasks: online.yml
  when: offline is not defined or not offline | bool

- name: Install binaries offline
  import_tasks: offline.yml
  when:
    - offline is defined
    - offline | bool

- name: Config nvidia runtime
  template: src=docker.j2 dest=/etc/docker/daemon.json

- name: Remove commandline runtimes
  shell: |
    sed -i '/--add-runtime/'d /usr/lib/systemd/system/docker.service 
    sed -i '/--default-runtime/'d /usr/lib/systemd/system/docker.service 

- name: Config nvidia docker2
  template: src=nvidia-docker dest=/usr/bin/nvidia-docker
  
- name: Reload and restart Docker engine
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker
