---

- name: Add Kubernetes APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: "{{ apt_key }}"
    state: present

- name: Add Kubernetes APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: "{{ apt_repo }}"
    state: present
    filename: 'kubernetes'

- name: Add Kubernetes yum repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: "{{ yum_repo }}"
    enabled: yes
    gpgcheck: no

- name: Disable selinux
  when: ansible_os_family == "RedHat"
  selinux: policy=targeted state=permissive

- name: Install kubernetes packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - yum-versionlock
    - kubectl-{{ yum_kubectl_version }}
    - kubelet-{{ yum_kubelet_version }}
    - kubernetes-cni-{{ yum_kubernetes_cni_version }}
    - kubeadm-{{ yum_kubeadm_version }}

- name: Lock the version of kubernetes packages
  when: ansible_os_family == "RedHat"
  shell: yum versionlock add kubectl kubelet kubernetes-cni kubeadm

- name: Install kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - kubectl={{ apt_kubectl_version }}
    - kubelet={{ apt_kubelet_version }}
    - kubernetes-cni={{ apt_kubernetes_cni_version }}
    - kubeadm={{ apt_kubeadm_version }}

- name: Lock the version of kubernetes packages
  when: ansible_os_family == "Debian"
  shell: apt-mark hold kubectl kubelet kubernetes-cni kubeadm

- name: Disable swap
  command: swapoff -a

# /dev/mapper/centos-swap swap swap ... (CentOS)
# /dev/mapper/vagrant--vg-swap_1 none swap ... (Ubuntu)
- name: Remove swap from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+[\S]+\s+swap '
    state: absent

- name: Pass bridged IPv4 traffic to iptables’ chains
  shell: "sysctl net.bridge.bridge-nf-call-iptables=1"

- name: Override config file directory for Debian
  when: ansible_os_family == "Debian"
  set_fact:
    dropin_dir: "/etc/systemd/system"

- name: Copy kubeadm conf to drop-in directory
  when: ansible_os_family == "Debian"
  template: src=10-kubeadm.conf.j2 dest={{ dropin_dir }}/kubelet.service.d/10-kubeadm.conf

- name: Enable and start kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

