- name: Disable selinux
  when: ansible_os_family == "RedHat"
  selinux: policy=targeted state=permissive

- name: Install binaries online
  import_tasks: online.yml
  when: offline is not defined or not offline | bool

- name: Install binaries offline
  import_tasks: offline.yml
  when:
    - offline is defined
    - offline | bool

- name: Lock the version of kubernetes packages
  when: ansible_os_family == "Debian"
  shell: apt-mark hold kubectl kubelet kubernetes-cni kubeadm

- name: Disable swap
  command: swapoff -a

# /dev/mapper/centos-swap swap swap ... (CentOS)
# /dev/mapper/vagrant--vg-swap_1 none swap ... (Ubuntu)
- name: Remove swap from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+[\S]+\s+swap '
    state: absent

- name: Pass bridged IPv4/IPv6 traffic to iptables’ chains
  shell: |
    sysctl net.bridge.bridge-nf-call-iptables=1
    sysctl net.bridge.bridge-nf-call-ip6tables=1

- name: Change vm.max_map_count to 262144
  shell: |
    sysctl vm.max_map_count=262144

- name: Set facts for Debian
  when: ansible_os_family == "Debian"
  set_fact:
    cgroup_driver: cgroupfs

- name: Set facts for RedHat
  when: ansible_os_family == "RedHat"
  set_fact:
    cgroup_driver: systemd

- name: Copy kubeadm conf to drop-in directory
  template: src=10-kubeadm.conf.j2 dest={{ dropin_dir }}/kubelet.service.d/10-kubeadm.conf
  when: kube_num_version | version_compare('1.8', '<')

- name: Copy kubeadm conf to drop-in directory (1.8 and later)
  template: src=10-kubeadm-post-1.8.conf.j2 dest={{ dropin_dir }}/kubelet.service.d/10-kubeadm.conf
  when: kube_num_version | version_compare('1.8', '>=')

- name: Enable and start kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

  
