---

- name: Add Kubernetes APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: "{{ apt_key }}"
    state: present

- name: Add Kubernetes APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: "{{ apt_repo }}"
    state: present
    filename: 'kubernetes'

- name: Add Kubernetes yum repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: "{{ yum_repo }}"
    enabled: yes
    gpgcheck: no

- name: Disable selinux
  when: ansible_os_family == "RedHat"
  selinux: policy=targeted state=permissive

- name: Install kubernetes packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - kubectl
    - kubelet
    - kubernetes-cni
    - kubeadm

- name: Install kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - kubectl
    - kubelet
    - kubernetes-cni
    - kubeadm

- name: Disable swap
  command: swapoff -a

# /dev/mapper/centos-swap swap swap ... (CentOS)
# /dev/mapper/vagrant--vg-swap_1 none swap ... (Ubuntu)
- name: Remove swap from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+[\S]+\s+swap '
    state: absent

- name: Enable and start kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

