- name: Create rpm directory
  file: path={{ ecp_rpm_dir }} state=directory

- name: Copy rpm files to all hosts
  synchronize:
    src: "{{ ecp_rpms }}"
    dest: "{{ ecp_rpm_dir }}"
    checksum: yes

- name: Install offline package
  when: 
    - ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ecp_rpm_dir }}/yum-plugin-versionlock-1.1.31-42.el7.noarch.rpm"
    - "{{ ecp_rpm_dir }}/kubectl-{{ yum_kubectl_version }}.x86_64.rpm"
    - "{{ ecp_rpm_dir }}/kubelet-{{ yum_kubelet_version }}.x86_64.rpm"
    - "{{ ecp_rpm_dir }}/kubernetes-cni-{{ yum_kubernetes_cni_version }}.x86_64.rpm"
    - "{{ ecp_rpm_dir }}/kubeadm-{{ yum_kubeadm_version }}.x86_64.rpm"

