---
- name: Create rpm directory
  file: path={{ rpm_dir }} state=directory

- name: Copy rpm files to all hosts
  synchronize:
    src: "{{ k8s_updrade_rpms_dir }}/"
    dest: "{{ rpm_dir }}"
    checksum: yes