---
- name: Reset Kubernetes component
  shell: "kubeadm reset"

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Join to Kubernetes cluster
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ token }} \
                 {{ vip }}:{{ nginx_port }}
  register: join_cluster

