---
- name: Check vip
  fail:
    msg: "You must define a virtual IP in the inventory file when more than one master host is defined."
  when: master_hosts|length > 1 and vip is not defined
  
- name: Deploy the primary master
  import_tasks: master.yml
  run_once: true
  delegate_to: "{{ master_hosts[0] }}"
