---
- name: Stop kubelet service
  shell: |
    service kubelet stop

- name: Create bin directory
  file: path=/opt/bins/ state=directory

- name: Copy bin to all hosts
  copy:
    src: "{{ item }}"
    dest: "/opt/bins/"
  with_items:
    - ../templates/bins.tar.gz

- name: Unpack bins
  unarchive: src=/opt/bins/bins.tar.gz dest=/opt/bins/

- name: Copy bin to /usr/bin/
  shell: |
    cp /opt/bins/kubelet /usr/bin/kubelet
    cp /opt/bins/kubectl /usr/bin/kubectl

- name: Start kubelet service
  shell: |
    service kubelet start
