---
- name: Stop kubelet service
  shell: |
    service kubelet stop

- name: Copy mount shell
  template: src={{ item }} dest=/usr/bin/
  with_fileglob:
    - ../bin/*

- name: Start kubelet service
  shell: |
    service kubelet start
