---
- name: Create license directory
  file: path={{ kube_ecp_dir }}/license state=directory

- name: Copy license yaml file
  template: src={{ item }} dest={{ kube_ecp_dir }}/license/{{ item | basename | regex_replace('\.j2', '') }}
  with_fileglob:
    - ../templates/license/*.j2

- name: Check if license rc already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get rc --namespace={{ ecp_namespace }} | grep firmament-license
  run_once: true
  register: check_license_rc
  failed_when: check_license_rc.rc != 0 and check_license_rc.rc != 1

- name: Create license rc
  when: check_license_rc|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/license/license-controller.yaml
  run_once: true

- name: Check if license service already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get svc --namespace={{ ecp_namespace }} | grep license-firmament-com
  run_once: true
  register: check_license_svc
  failed_when: check_license_svc.rc != 0 and check_license_svc.rc != 1

- name: Create license svc
  when: check_license_svc|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/license/license-service.yaml
  run_once: true

