---
- name: Create mysql directory
  file: path={{ kube_ecp_dir }}/mysql state=directory

- name: Copy mysql yaml file
  template: src={{ item }} dest={{ kube_ecp_dir }}/mysql/{{ item | basename | regex_replace('\.j2', '') }}
  with_fileglob:
    - ../templates/mysql/*.j2

- name: Check if mysql rc already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get rc --namespace={{ ecp_namespace }} | grep firmament-mysql
  run_once: true
  register: check_mysql_rc
  failed_when: check_mysql_rc.rc != 0 and check_mysql_rc.rc != 1

- name: Create mysql rc
  when: check_mysql_rc|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/mysql/mysql-controller.yaml
  run_once: true

- name: Check if mysql service already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get svc --namespace={{ ecp_namespace }} | grep firmament-mysql
  run_once: true
  register: check_mysql_svc
  failed_when: check_mysql_svc.rc != 0 and check_mysql_svc.rc != 1

- name: Create mysql svc
  when: check_mysql_svc|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/mysql/mysql-service.yaml
  run_once: true

