---
- name: Create operator directory
  file: path={{ kube_ecp_dir }}/redis-operator state=directory

- name: Copy redis-operator yaml file
  template: src={{ item }} dest={{ kube_ecp_dir }}/redis-operator/{{ item | basename | regex_replace('\.j2', '') }}
  with_fileglob:
    - ../templates/redis-operator/*.j2

- name: Check if redis operator service account already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get sa --namespace=kube-system | grep operator
  run_once: true
  register: check_operator_sa
  failed_when: check_operator_sa.rc != 0 and check_operator_sa.rc != 1

- name: Create RBAC
  when: check_operator_sa.rc != 0
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/redis-operator/operator-k8s-rbac.yaml
  run_once: true

- name: Check if redis operator deployment already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get deployment --namespace=kube-system | grep operator
  run_once: true
  register: check_operator_deploy
  failed_when: check_operator_deploy.rc != 0 and check_operator_deploy.rc != 1

- name: Create deployment
  when: check_operator_deploy.rc != 0
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/redis-operator/operator-deployment.yaml
  run_once: true

- name: Wait until operator pod starts to run
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get po --namespace=kube-system | grep operator
  register: check_operator
  until: check_operator.rc == 0 and check_operator.stdout.find("Running") != -1
  retries: "{{ pod_run_retry | int }}"
  delay: "{{ pod_run_retry_delay | int }}"



