---
- name: Create river directory
  file: path={{ kube_ecp_dir }}/river state=directory

- name: Copy river yaml file
  template: src={{ item }} dest={{ kube_ecp_dir }}/river/{{ item | basename | regex_replace('\.j2', '') }}
  with_fileglob:
    - ../templates/river/*.j2

- name: Check if river service account already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get sa --namespace={{ ecp_namespace }} | grep river
  run_once: true
  register: check_river_sa
  failed_when: check_river_sa.rc != 0 and check_river_sa.rc != 1

- name: Create RBAC
  when: check_river_sa|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/river/river-k8s-rbac.yaml
  run_once: true

- name: Check if river deployment already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get deployment --namespace=kube-system | grep river
  run_once: true
  register: check_river_deploy
  failed_when: check_river_deploy.rc != 0 and check_river_deploy.rc != 1

- name: Create river deployment
  when: check_river_deploy|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/river/river-deployment.yaml
  run_once: true

- name: Check if river service already exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get svc --namespace=kube-system | grep river
  run_once: true
  register: check_river_svc
  failed_when: check_river_svc.rc != 0 and check_river_svc.rc != 1

- name: Create river svc
  when: check_river_svc|failed
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            create -f {{ kube_ecp_dir }}/river/river-service.yaml
  run_once: true

- name: Wait until river pod exists
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
            get po --namespace=kube-system | grep river
  register: check_river
  until: check_river.rc == 0 and check_river.stdout.find("Running") != -1
  retries: "{{ pod_run_retry | int }}"
  delay: "{{ pod_run_retry_delay | int }}"



