---
kube_num_version: "{{ kube_version | replace('v', '') }}"
master_hosts: "{{ groups.masters | default([]) }}"
worker_hosts: "{{ groups.workers | default([]) }}"
cluster_hosts: "{{ groups.cluster | default([]) }}"
new_worker_hosts: "{{ groups.new_workers | default([]) }}"
glusterfs_hosts: "{{ groups.glusterfs | default([]) }}"
gpu_hosts: "{{ groups.gpu | default([]) }}"
